method: rs  # (Augmented) random search.

out_dir: './experiments/rl_experiments/walker/rs/'

environment_name: Walker2d-v1
mlp:
    layers: [17,6]
    add_bias: True
    state_normalization: True
    manipulate_reward: 
        shift: 1
        scale: 

trials: 3
# Either choose max_iterations or max_objective_calls unequal None.
max_iterations: 
max_objective_calls: 75000

optimizer_config:
    step_size: 0.03
    samples_per_iteration: 40
    exploration_noise: 0.025
    standard_deviation_scaling: True
    num_top_directions: 30
    param_args_ignore: [-1, -2, -3, -4, -5, -6]
    verbose: True
