method: rs  # (Augmented) random search.

out_dir: './experiments/rl_experiments/ant/rs/'

environment_name: Ant-v1
mlp:
    layers: [111, 8]
    add_bias: True
    state_normalization: True
    manipulate_reward: 
        shift: 1
        scale: 

trials: 3
# Either choose max_iterations or max_objective_calls unequal None.
max_iterations: 
max_objective_calls: 75000

optimizer_config:
    step_size: 0.015
    samples_per_iteration: 60
    exploration_noise: 0.025
    standard_deviation_scaling: True
    num_top_directions: 20
    param_args_ignore: [-1, -2, -3, -4, -5, -6, -7, -8]
    verbose: True
