method: cmaes  # Covariance matrix adaptation.

out_dir: './experiments/synthetic_experiments/050821/cmaes/'

# Either choose max_iterations or max_objective_calls not None.
max_iterations: 
max_objective_calls: 300

optimizer_config:
    sigma: 0.5 
